[theme]
primaryColor = "#262730"
backgroundColor = "#1a1a1a"
secondaryBackgroundColor = "#2b2b3b"
textColor = "#ffffff"
font = "sans serif"

[client]
showErrorDetails = false
showWarningOnDirectExecution = false

[logger]
level = "info"

[server]
port = 8501
headless = true
runOnSave = true
